.gitignore
.gitignore 수정
- .idea/
- .python-version
=> [develop] update .gitignore

backend/mysite/settings.py, backend/poetry.lock, backend/pyproject.toml, backend/users/admin.py, backend/users/apps.py, backend/users/models.py, backend/users/tests.py, backend/users/views.py
settings에 db 환경변수 설정
- mysqlclient 설치
- db 환경변수 설정
- startapp users
closes #13
=> [Feature/db setting] DB 세팅 완료

frontend/src/App.tsx, frontend/src/Components/Topnav.tsx, frontend/src/Pages/Login/index.css, frontend/src/Pages/Login/index.tsx, frontend/src/Pages/Main/Index.tsx, frontend/src/Pages/Meet/Index.css, frontend/src/Pages/Meet/Index.tsx, frontend/src/Pages/Signup/index.css, frontend/src/Pages/Signup/index.tsx, frontend/src/index.css
컴포넌트 인식 이슈 파일명을 바꾸고 다시 index로,
따옴표 수정
따옴표,컴포넌트 미인식 해결
- import 된 컴포넌트 재정렬
- Pages에 있는 index.tsx , index.css 제목명 변경 후 다시 index로 만들었음.
- 
- 
-
=> [Feature/login-fe]: 인식오류해결

frontend/src/App.tsx, frontend/src/Components/Topnav.tsx, frontend/src/Pages/Meethome/index.css, frontend/src/Pages/Meethome/index.tsx, frontend/src/Pages/Mymeet/index.tsx
App.tsx에 라우터 생성 
- App.tsx에 Meethome 생성
- 
- 
- 
-
=> [Feature/meet fe] 라우터 생성 

frontend/src/App.tsx, frontend/src/Components/Footer.css, frontend/src/Components/Topnav.tsx, frontend/src/Pages/Createmeet/index.css, frontend/src/Pages/Createmeet/index.tsx, frontend/src/Pages/Main/index.css
Main 페이지 height 수정
-  Main 페이지 height 수정
-  라우트 목록 수정
- 
- 
-
=> [Feature/create meet fe] Main 페이지 height 수정

backend/app/album/models.py, backend/app/board/admin.py, backend/app/board/models.py, backend/app/board/permissions.py, backend/app/board/serializers.py, backend/app/board/urls.py, backend/app/board/views.py, backend/app/club/models.py, backend/app/club/serializers.py, backend/app/club/views.py, backend/app/user/models.py, backend/app/user/permissions.py, backend/app/user/views.py, backend/mysite/settings.py, backend/mysite/urls.py
게시판 기능
- 일반 게시판(Post)
- 일정 게시판(Schedule)
- post, schedule, album, user 모델 수정
- board, photo 모델 삭제
- agegroup 모델 추가
- 
- 
closes #49
=> [Feature/board be] update board app

frontend/.eslintrc.cjs, frontend/src/App.tsx, frontend/src/Context/Handleimgchange.tsx, frontend/src/Context/Token.tsx, frontend/src/Pages/Boardwrite/Onclickboard.tsx, frontend/src/Pages/Boardwrite/index.css, frontend/src/Pages/Boardwrite/index.tsx, frontend/src/Pages/Createmeet/index.css, frontend/src/Pages/Createmeet/index.tsx, frontend/src/Pages/Login/index.tsx, frontend/src/Pages/Main/Moveimages.tsx, frontend/src/Pages/Main/index.css, frontend/src/Pages/Main/moveimages.css
axios로 access토큰 요청 코드 작성
로그인 acess토큰 받기
-  axios  에세스토큰 코드만 작성
- 
- 
- 
-
=> [feaure/create-meet-func-fe] 로그인 서버 연결 코드작성

backend/app/album/models.py, backend/app/board/models.py, backend/app/board/permissions.py, backend/app/board/serializers.py, backend/app/board/tests.py, backend/app/board/views.py, backend/app/category/tests.py, backend/app/club/serializers.py, backend/app/club/tests.py, backend/app/user/tests.py, backend/mysite/settings.py, backend/mysite/urls.py, backend/poetry.lock, backend/pyproject.toml, backend/test.sh
테스트 코드 작성
- coverage 설치
- user, post, schedule, category, club test
- isort, black, mypy
=> [Feature/testcode-be] add test code

backend/app/comment/permissions.py, backend/app/comment/serializers.py, backend/app/comment/urls.py, backend/app/comment/views.py, backend/entrypoint.sh, backend/mysite/settings.py, backend/mysite/urls.py, backend/poetry.lock, backend/pyproject.toml
댓글 기능
- 댓글 기능 구현
- django-cors-headers 설치하고 세팅
- user 에러처리 해야함
- 
closes #54
=> [Feature/comment be] implement comment

frontend/package.json, frontend/src/App.tsx, frontend/src/Context/Authuser.tsx, frontend/src/Context/Token.tsx, frontend/src/Pages/Login/index.css, frontend/src/Pages/Login/index.tsx, frontend/src/Pages/Main/newpost.tsx, frontend/src/Pages/Signup/index.css, frontend/src/Privateroute/Privateroute.tsx, frontend/src/Type/User.d.ts, frontend/yarn.lock
회원일 땐 모든 페이지 접속가능 ,
로그인 하지 않았을 땐 로그인페이지,회원가입페이지만 접속 가능
Route 회원전용 페이지 구현
- 로그인 되어있을 때 로그인페이지,회원가입 페이지 접속 불가
- 로그인 안되어있을 때 main페이지 , 로그인페이지,회원가입 페이지를 제외한 곳들 접속 불가
- 
- 
-
=> Feat: 회원전용 페이지 구현

backend/app/activity/models.py, backend/app/activity/serializers.py, backend/app/activity/urls.py, backend/app/activity/views.py, backend/app/category/models.py, backend/app/club/models.py, backend/app/club/serializers.py, backend/app/user/adapters.py, backend/app/user/admin.py, backend/app/user/models.py, backend/app/user/serializers.py, backend/mysite/settings.py
회원 가입 필수 입력 조건 변경
- profession 필드 입력 선택으로 바꿈
- club 생성할때 연령대 추가
- 토큰 쿠키에 저장하지 않도록 함
- 모임 가입 기능 추가한것처럼 보이나 아직 안한것임
- 연령대 조건 추가해야함
=> [Feature/changed-requirements-be] 변경된 요구사항 수정 및 버그 수정

frontend/src/Apis/axios.ts, frontend/src/App.tsx, frontend/src/Components/Topnav.css, frontend/src/Components/Topnav.tsx, frontend/src/Pages/Createmeet/index.tsx, frontend/src/Pages/Login/index.tsx, frontend/src/Pages/Main/newpost.tsx
header를 context에 넣어서 access토큰을 전역으로 설정
리액트 Access토큰 전역으로 설정
- axios.ts에 전역으로 설정
- createboard 코드에 서버로 보내는 코드 수정
- 
-  몇가지 형식이 백엔드와 맞지 않아서 아직 서버에 보내지지 않으니 이 점 논의해야 함.
-
=> [feature/storage-fe] 리액트 토큰 전역으로 설정

backend/.gitignore, backend/mysite/settings.py
로깅 설정
settings.py
- LOGGING 설정에서 파일에 기록하는 핸들러 추가
- DEBUG=False일때 콘솔에 로그 출력 안되게 함
.gitignore
- logs 디렉토리 추가
- 
-
=> [Feature/logging-be] LOGGING 설정 변경

backend/app/activity/admin.py, backend/app/album/admin.py, backend/app/board/admin.py, backend/app/board/models.py, backend/app/comment/admin.py, backend/app/common/admin.py
album, activity, board, comment admin 설정
- album, activity, board, comment 어드민 페이지 추가
- 
- 
- 
-
=> [Feature/admin-be]admin_page설정

frontend/src/App.tsx, frontend/src/Pages/Createboard/index.tsx, frontend/src/Pages/Createmeet/index.tsx, frontend/src/Type/User.d.ts
게시글에 사진은 제외한 title,content를 서버전송 성공
게시글 쓰기 서버 연동
- 게시글쓰기 title,content 서버연동 (사진 제외)
-  
- 
- 사진연동
-
=> [Feature/createboard-func-fe] 게시글 쓰기 서버 연동

backend/app/activity/admin.py, backend/app/activity/permissions.py, backend/app/activity/serializers.py, backend/app/activity/urls.py, backend/app/activity/utils.py, backend/app/activity/views.py, backend/app/board/serializers.py, backend/app/category/views.py, backend/app/comment/serializers.py, backend/app/user/views.py, backend/entrypoint.sh, backend/mysite/settings/base.py, backend/mysite/urls.py
가입 모임 목록, 모임 가입, 모임 탈퇴 기능 구현
- 가입 모임 목록 유저별로 볼수 있는 기능 GET /users/{user_id}/clubs
- 모임에 가입할 수 있는 기능  POST /clubs/{club_id}/join
- 가입한 모임에서 탈퇴할 수 있는 기능  DELETE /clubs/{club_id}/leave
- 이미 가입한 모임 중복 가입 불가능하게 해야함
- 
closes #68
=> [Feature/join-club-be] 가입 모임 목록, 모임 가입, 모임 탈퇴 기능 구현

frontend/src/Apis/axios.ts, frontend/src/App.tsx, frontend/src/Pages/Clubcategory/index.css, frontend/src/Pages/Clubcategory/index.tsx, frontend/src/Pages/Clubuserlist/index.tsx, frontend/src/Pages/Createboard/index.css, frontend/src/Pages/Createmeet/index.tsx, frontend/src/Pages/Login/index.tsx, frontend/src/Pages/Main/Categoryicons.css, frontend/src/Pages/Main/Categoryicons.tsx, frontend/src/Pages/Main/Moveimages.tsx, frontend/src/Pages/Main/Newpost.css, frontend/src/Pages/Main/index.css, frontend/src/Pages/Main/index.tsx, frontend/src/Pages/Main/moveimages.css, frontend/src/Pages/Main/newpost.tsx, frontend/src/Pages/Meethome/Home.tsx, frontend/src/Pages/Meethome/index.css, frontend/src/Pages/Meethome/index.tsx, frontend/src/Type/vite-env-d.ts
메인페이지가 최신이 뜨게 데이터바인딩
메인페이지가 최신이 뜨게 데이터바인딩
- 메인페이지 데이터바인딩
- .env파일 수정
-  
- 
-
=> [Feature/categorypage-fe] 메인페이지 데이터바인딩

frontend/.eslintrc.cjs, frontend/src/App.tsx, frontend/src/Components/Nationoption/Selectbox.tsx, frontend/src/Pages/Login/index.tsx, frontend/src/Pages/Main/Moveimages.css, frontend/src/Pages/Main/Newpost.tsx, frontend/src/Pages/Main/index.tsx, frontend/src/Pages/Myinfo/index.css, frontend/src/Pages/Myinfo/index.tsx, frontend/src/Pages/Signup/index.css, frontend/src/Pages/Signup/index.tsx, frontend/src/Type/User.d.ts
내 정보수정 페이지 css완료 및 유효성 검사 완료, 회원가입 비밀번호 보이게, 메인페이지 파일 이름 수정
- 내 정보수정 페이지 css완료 및 유효성 검사 완료
- 회원가입 비밀번호 보이게, 아이콘 삽입
- 메인페이지 파일 이름 수정
- 
-
=> [Feature/myinfo func fe]  내정보수정 및 회원가입

backend/app/activity/urls.py, backend/app/activity/views.py, backend/app/club/serializers.py, backend/app/user/serializers.py, backend/app/user/urls.py, backend/app/user/views.py, backend/mysite/urls.py
api uri 정리
- UserSerializer를 CustomUserDetail로 변경
- user앱에 있는 user -> accounts, accounts 앱에 있는 user -> activities
- user_id 다 뺌
- 회원 탈퇴 기능 수정
- 가입한 모임 목록 /activities/clubs로 변경
- 회원 탈퇴 /accounts/user로 변경
=> [Feature/endpoint-be] api uri 정리

frontend/src/Pages/Login/index.tsx, frontend/src/Pages/Signup/index.tsx
프론트 빌드를 위한 pr요청
프론트 빌드 테스트
- 빌드를 위해 수정 , 빌드 실행
- 
- 
- 
-
=> [feature/bugfix-fe]프론트 빌드 테스트

frontend/netlify.toml
netlify.toml 추가
프론트 배포 테스트
- 프론트 배포를 위한 netlify.toml 추가
- 
- 
- 
-
=> [feature/bugfix-fe]프론트 배포 테스트

frontend/netlify.toml
프론트엔드 배포 테스트
프론트엔드 배포 테스트
-  netlify.toml에 텍스트 추가
- 
- 
- 
-
=> [feature/bugfix-fe]프론트엔드 배포 테스트

backend/app/activity/serializers.py, backend/app/activity/urls.py, backend/app/activity/views.py, backend/app/board/models.py, backend/app/board/permissions.py, backend/app/board/serializers.py, backend/app/comment/permissions.py, backend/mysite/settings/base.py
기능 추가
- 게시글에 사진 한장 올리기 기능
- 내가 작성한 글, 댓글 모아보기 기능
- 게시글, 댓글 권한 수정
- 앨범기능 만들 예정
-
=> [Feature/post-photo-be] 게시글에 사진 등록 기능, 작성글, 댓글 보기 기능 추가

frontend/src/App.tsx, frontend/src/Components/Nationoption/Selectbox.tsx, frontend/src/Pages/Meethome/MemberList.css, frontend/src/Pages/Meethome/MemberList.tsx, frontend/src/Pages/Meethome/index.tsx, frontend/src/Pages/Myinfo/index.css, frontend/src/Pages/Myinfo/index.tsx, frontend/src/Pages/Signup/Success.tsx, frontend/src/Pages/Signup/index.css, frontend/src/Pages/Signup/index.tsx, frontend/src/Type/User.d.ts
내정보수정페이지 완성 및 모임 멤버리스트 페이지 구현
myinfo 완성
- myinfo 완성
- signup css 변경
- meethome 멤버리스트 페이지 설정
- 
-
=> [feature/updatemyinfo-fe] myinfo 완성

frontend/src/Pages/Createboard/index.tsx, frontend/src/Pages/FeedScreen/CommentList.css, frontend/src/Pages/FeedScreen/index.css, frontend/src/Pages/FeedScreen/index.tsx, frontend/src/Pages/Meethome/Home.tsx, frontend/src/Pages/Meethome/NoticeBox.tsx, frontend/src/Pages/Meethome/index.css, frontend/src/Pages/Meethome/index.tsx, frontend/src/Pages/Mymeet/index.tsx
모임가입을 해야 데이터 바인딩을 할수있어서
-모임가입하기 기능을 수행
- 피드 상세페이지 댓글기능 수정 
- 
- 
-
=> [feature/feedscreen-fe] 모임가입하기 기능, 피드 상세페이지 댓글기능 수정

frontend/src/Apis/axios.ts, frontend/src/App.tsx, frontend/src/Components/Getaccess.tsx, frontend/src/Components/Topnav.tsx, frontend/src/Pages/Clubcategory/index.tsx, frontend/src/Pages/Createboard/index.tsx, frontend/src/Pages/Main/NewPost.tsx, frontend/src/Pages/Main/Newpost.css, frontend/src/Pages/Meethome/index.tsx, frontend/src/Pages/Mymeet/index.css, frontend/src/Pages/Mymeet/index.tsx, frontend/src/Type/User.d.ts
-access토큰이 만료되면 refresh 토큰을 통해서 재발급 받는 코드 작성
-나의모임 아이콘에 데이터 바인딩
-글 작성 후에 useNavigate 설정
-createBoard에 Route /:id 추가
- access토큰 재발급 코드 작성
- 나의모임에 아이콘 데이터바인딩
- -글 작성 후에 useNavigate 설정
- createBoard에 Route /:id 추가
- 
-
=> [Feature/release-fe] access토큰 재발급 요청 및 데이터 바인딩

frontend/src/Pages/Meethome/NoticeBoard.tsx, frontend/src/Pages/Meethome/index.tsx, frontend/src/Type/Meethome.d.ts
feedData값을 읽을 수 없어서 읽도록 수정
- feedData any타입지정
- props전송을 위해 인자로 내려주는 작업
- 
- 
-
=> [feature/datas-fe] feedData 타입 오류

frontend/src/Pages/Clubcategory/index.tsx, frontend/src/Pages/Createboard/index.tsx, frontend/src/Pages/Main/Moveimages.tsx, frontend/src/Pages/Main/NewPost.tsx, frontend/src/Pages/Meethome/index.tsx, frontend/src/Pages/Myinfo/index.tsx, frontend/src/Pages/Mymeet/index.tsx, frontend/src/Pages/Signup/index.tsx
- 프론트에서 작성한 콘솔로그 삭제
- 
- 
- 
-
=> [feature/datas-fe] 프론트엔드 콘솔로그 삭제

frontend/src/App.tsx, frontend/src/Pages/Createschedules/index.tsx, frontend/src/Pages/Meethome/Schedule.tsx
일정 등록페이지에서 서버로 보내는 것을 구현
- 일정만드는 페이지 서버로 보내기 성공
- 모임 홈화면에서 일정만들기 누르면 , 일정만드는 페이지로 보내기 구현
- 
- 
-
=> [feature/datas-fe] 일정 등록하기

backend/app/activity/serializers.py, backend/app/activity/urls.py, backend/app/activity/views.py, backend/app/album/views.py, backend/app/board/views.py, backend/app/club/views.py, backend/app/comment/views.py, backend/app/user/adapters.py, backend/app/user/serializers.py, backend/mysite/settings/base.py, backend/poetry.lock, backend/pyproject.toml
- 가입한 모임에 올라온 글 모아보기
- 댓글, 글, 일정, 모임 목록 등 정렬
- 비밀번호 수정 안되던 문제 해결
- 이미지 삭제하면 버킷에 있는 이미지도 같이 삭제되도록 함
- 
-
=> [Feature/feed-be] 피드 기능, 정렬, 비밀번호 수정 문제

frontend/src/Components/Deletemember.css, frontend/src/Components/Deletemember.tsx, frontend/src/Components/Footer.css, frontend/src/Components/Footer.tsx, frontend/src/Components/Topnav.tsx, frontend/src/Pages/Meethome/MemberList.css, frontend/src/Pages/Meethome/MemberList.tsx, frontend/src/Pages/Myinfo/index.css, frontend/src/Pages/Myinfo/index.tsx, frontend/src/Pages/Mymeet/index.css, frontend/src/Pages/Signup/index.tsx
네브바 스타일 변경 및 탈퇴하기 버튼 생성
네브바 스타일 변경, 탈퇴하기 버튼
- 네브바 스타일 변경
- 내 정보수정에 탈퇴하기 버튼 
- 
- 탈퇴하기 기능 완성
-
=> [feature/updateTopnav] 네브바 스타일 변경

frontend/src/Pages/Meethome/Album.css, frontend/src/Pages/Meethome/Album.tsx, frontend/src/Pages/Meethome/Home.tsx, frontend/src/Pages/Meethome/NoticeBoard.css, frontend/src/Pages/Meethome/NoticeBoard.tsx, frontend/src/Pages/Meethome/NoticeBox.tsx, frontend/src/Pages/Meethome/Schedule.css, frontend/src/Pages/Meethome/Schedule.tsx, frontend/src/Pages/Meethome/ScheduleBox.tsx, frontend/src/Pages/Meethome/index.css, frontend/src/Pages/Meethome/index.tsx
스크린 사이즈에 따라 보여지는 부분이 다르게 하기 위해
- meethome 페이지에서 홈, 게시글, 엘범 부분의 반응형 스타일 적용 
- 아이콘 정렬
- 
- 
-
=> [feature/screen-fe] meetHome 반응형 스타일 수정

backend/app/activity/urls.py, backend/app/activity/views.py, backend/app/album/admin.py, backend/app/album/models.py, backend/app/club/urls.py, backend/app/user/urls.py
- activity, club, user/urls.py
- 슬래시 추가
album/admin.py
- AlbumAdmin 제거
album/models.py
- Album 모델 제거
JoinClub
- 중복가입 에러코드 409로 변경
- 
-
=> [Bugfix/user-bug-be] url 수정, 안쓰는 모델 제거

frontend/src/Pages/Clubcategory/index.tsx, frontend/src/Pages/Meethome/Album.tsx, frontend/src/Pages/Meethome/MemberList.tsx, frontend/src/Pages/Meethome/index.tsx, frontend/src/Pages/Myinfo/index.tsx, frontend/src/Pages/Mymeet/index.tsx
=> [bugfix/uri-fe] endpoint 수정

frontend/src/Pages/FeedScreen/Commentfunc.tsx, frontend/src/Pages/Main/Categoryicons.tsx, frontend/src/Pages/Main/Moveimages.tsx, frontend/src/Pages/Main/NewPost.tsx, frontend/src/Pages/Main/index.tsx, frontend/src/Pages/Meethome/NoticeBoard.tsx, frontend/src/Pages/Meethome/NoticeBox.tsx, frontend/src/Pages/Meethome/Schedule.tsx
fetchComments 함수를 단한번만 구현되도록
- fetchComments 함수가 반복렌더링 되어서 한번 렌더링 되게 수정
- 
- 
- 
-
=> [feature/func-feed-fe] 게시판 댓글 컴포넌트 반복렌더링 수정

frontend/src/Components/Deletemember.css, frontend/src/Components/Deletemember.tsx, frontend/src/Pages/Meethome/MemberList.css, frontend/src/Pages/Meethome/MemberList.tsx, frontend/src/Pages/Meethome/index.tsx, frontend/src/Pages/Myinfo/index.css, frontend/src/Pages/Myinfo/index.tsx, frontend/src/Pages/Mymeet/index.css, frontend/src/Pages/Signup/Success.tsx, frontend/src/Pages/Signup/index.tsx, frontend/src/Type/User.d.ts
내정보수정 사진 수정하기 버그수정,이메일표시,모임 멤버리스트인원표시
myinfo 사진수정,이메일가져오기,memberList count
- 내정보수정 사진 버그 수정, 이메일 가져와서 표기
- 모임 멤버리스트 인원 표기
- 탈퇴하기 후 토큰 없애고 자동으로 로그아웃 
- 
-
=> [feature/deleteBtn-fe] myinfo 사진수정,이메일가져오기,memberList count

frontend/src/Pages/Createschedules/index.tsx, frontend/src/Pages/FeedScreen/Commentfunc.tsx
utc +9로 한국시간으로 설정
- 일정만들기에서 시간 오류 수정
- 
- 
- 
-
=> [feature/func-feed-fe] 일정만들기 시간설정 오류 해결

frontend/src/Components/Topnav.css, frontend/src/Pages/Meethome/Album.css, frontend/src/Pages/Meethome/Album.tsx, frontend/src/Pages/Meethome/Home.css, frontend/src/Pages/Meethome/Home.tsx, frontend/src/Pages/Meethome/HomeMember.css, frontend/src/Pages/Meethome/HomeMember.tsx, frontend/src/Pages/Meethome/NoticeBoard.css, frontend/src/Pages/Meethome/NoticeBoard.tsx, frontend/src/Pages/Meethome/NoticeBox.tsx, frontend/src/Pages/Meethome/Schedule.css, frontend/src/Pages/Meethome/Schedule.tsx, frontend/src/Pages/Meethome/ScheduleBox.tsx, frontend/src/Pages/Meethome/index.css, frontend/src/Pages/Meethome/index.tsx, frontend/src/Pages/Mymeet/TabButton.css
- 미트홈 아이콘 미디어 쿼리 적용 
- 일정 시간 UI 
- 
- 
-
=> [Feature/meethome-style-fe] 미트홈 스타일 변경, 일정 시간 UI

README.md
README.md 수정
- 다이어그램 추가
- 레이아웃 정리
- 스택 추가
=> [Feature/readme] README.md 수정

backend/app/board/serializers.py
PostSerializer
- writer_image ImageField로 추가
- 게시글 쓸때 프로필 사진 필요
post에 유저 프로필 사진 추가
=> [Feature/other-rq-be] Post에 유저 프로필 사진 추가

frontend/src/Pages/FeedScreen/Commentfunc.tsx, frontend/src/Pages/FeedScreen/index.tsx
- 댓글 수정기능 구현
- 댓글 삭제기능 구현
- 댓글 CRUD 디자인 hide구현
- 
-
=> [Feature/feed-func-fe] 피드스크린 CRUD 구현

frontend/src/Components/Getaccess.tsx, frontend/src/Pages/Meethome/Album.tsx, frontend/src/Pages/Meethome/HomeMember.tsx, frontend/src/Pages/Meethome/MemberList.tsx, frontend/src/Pages/Meethome/index.tsx, frontend/src/main.tsx
=> [featrue/end-fe] 프론트엔드 콘솔로그 제거

frontend/src/Pages/Meethome/Home.tsx, frontend/src/Pages/Meethome/NoticeBox.tsx
프로필 사진 데이터를 가지고와서 추가시킴
- 피드 쓴 사람 프로필사진 보이게 데이터 바인딩함
- 
- 
- 
-
=> [feature/meethome-style-fe]  피드 쓴 사람 프로필사진 데이터 바인딩

frontend/src/Pages/Meethome/Schedule.css, frontend/src/Pages/Myinfo/index.tsx, frontend/src/Pages/Mymeet/index.css, frontend/src/Pages/Signup/index.css, frontend/src/Pages/Signup/index.tsx, frontend/src/Type/User.d.ts
myinfo typescript error 수정
- 내정보수정 타입스크립트 오류 수정
- 
- 
- 
-
=> [Feature/createMeet-fe] typescript error수정
